// SPLASHSCREENS
export 'splash/splash_screen.dart';
// ONDOARDING
export 'onboard/screens/onboard1.dart';
export 'onboard/screens/onboard2.dart';
export 'onboard/screens/onboard3.dart';
export 'onboard/screens/onboard4.dart';
export 'onboard/onboard_controller.dart';
// AUTH
export '../../presentation/screens/auth/login/screens/welcome_login.dart';
export 'auth/signup/screens/sign_up.dart';
export 'auth/recover/forgot_password.dart';
export 'auth/recover/set_password.dart';
// SETUP
export 'setup/walkway_controller.dart';
export 'setup/screens/walkway/welcome_setup.dart';
export 'setup/screens/walkway/select_age.dart';
export 'setup/screens/walkway/fill_profile.dart';
export 'setup/screens/walkway/select_activity_level.dart';
export 'setup/screens/walkway/select_goal.dart';
export 'setup/screens/walkway/select_gender.dart';
export 'setup/screens/walkway/select_weight.dart';
export 'setup/screens/walkway/select_height.dart';
// HOME
export 'home/screens/home_view.dart';
